
CREATE TABLE user (ID NUMBER, USERNAME VARCHAR(255), FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), EMAIL VARCHAR(255) UNIQUE, PASSWORD VARCHAR(255), CREATED_DATE DATE, PHONE_NUMBER VARCHAR(255));
INSERT INTO user (ID,USERNAME,FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, CREATED_DATE, PHONE_NUMBER) VALUES(123,'Kelvin1','Kelvin', 'Geek', 'kel@gmail.com', 'password-hash', CURRENT_DATE(), '08091714477');
INSERT INTO user (ID,USERNAME,FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, CREATED_DATE, PHONE_NUMBER) VALUES(124,'Kelvin2','Kelvin', 'Geek', 'kel2@gmail.com', 'password-hash', CURRENT_DATE(), '08091714477');

CREATE TABLE order_ (ID NUMBER, USER_ID NUMBER, OFFICE_DELIVERY BOOL, CARD_PAYMENT BOOLEAN, SHIPPING_ADDRESS VARCHAR(255), CREATED_DATE DATE, ORDER_TOTAL NUMBER);
INSERT INTO order_ (ID, USER_ID, OFFICE_DELIVERY, CARD_PAYMENT, SHIPPING_ADDRESS, CREATED_DATE, ORDER_TOTAL) VALUES(1,1,true,true,'6 Kamal Street', CURRENT_DATE(), 12345);

CREATE TABLE role (ID NUMBER, NAME VARCHAR(255), AB NUMBER);
/*INSERT INTO role (ID, NAME, AB) VALUES(0,'VENDOR', 1), (1,'DEV', 2);*/
CREATE TABLE meal (ID NUMBER, NAME VARCHAR(255) UNIQUE, PRICE NUMBER, ORDER_ID NUMBER, FOREIGN KEY (ORDER_ID) REFERENCES order_ (ID));
INSERT INTO meal (ID, NAME, PRICE, ORDER_ID) VALUES(101, 'Rice', 500, 1);

/*CREATE TABLE meal (ID NUMBER, NAME VARCHAR(255), PRICE NUMBER);
INSERT INTO meal (ID, NAME, PRICE) VALUES(101, 'Rice', 500);
INSERT INTO meal (ID, NAME, PRICE) VALUES(102, 'Beans', 100);
INSERT INTO meal (ID, NAME, PRICE) VALUES(103, 'Amala', 300);
INSERT INTO meal (ID, NAME, PRICE) VALUES(104, 'Chicken', 900);
INSERT INTO meal (ID, NAME, PRICE) VALUES(105, 'Beef', 500);
INSERT INTO meal (ID, NAME, PRICE) VALUES(106, 'Ponmo', 200);*/